version: '3'

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  wait_postgres:
    image: "waisbrot/wait"
    environment:
      TARGETS: postgres:5432

networks:
  default:
    driver: bridge
